# Base Python image
FROM python:3.10-slim

# Work directory
WORKDIR /app

# Copy requirement file & install Flask
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy app code
COPY . .

# Expose port
EXPOSE 5000

# Start app
CMD ["python", "app.py"]
